services:
  # mysql:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Meticulous%4013
  #     MYSQL_DATABASE: gb
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql  # Persist MySQL data

  backend:
      build: .
      command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
      ports:
        - "8000:8000"
    # depends_on:
    #   - mysql
    # environment:
    #   DATABASE_URL: mysql://root:Meticulous%4013@mysql:3306/gb  # Use fixed credentials
    # command: > 
    #   sh -c "while ! nc -z mysql 3306; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000"
# volumes:
#   mysql_data:
