services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Meticulous%4013
      MYSQL_DATABASE: gb
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:Meticulous%4013@localhost/db:3306  # Updated

volumes:
  mysql_data:
